import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { FaEnvelope } from 'react-icons/fa';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">aploskod!</a>
        </h1>

        <p className={styles.description}>
          We are currently under development &#128556;{' '}
        </p>
        <img src="/code.gif" alt="coding" width={72} height={36} />

        <h4 className={styles.messsage}>
          But not to worry! We will be back online very shortly!
        </h4>

        <div className={styles.grid}>
          <a href="mailto:dovlat93@gmail.com" className={styles.card}>
            <h2>
              Contact Us <FaEnvelope />
            </h2>
            <p>Send your inquiries via email.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://aploskod.no" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <Image
            src="/aploskod.png"
            alt="aploskod logo"
            width={35}
            height={31}
          />
        </a>
      </footer>
    </div>
  );
};

export default Home;
